# Generated by Django 3.2.19 on 2023-05-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        ('profiles', '0002_auto_20230513_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='profile',
            name='workspaces',
            field=models.ManyToManyField(blank=True, to='workspaces.Workspace'),
        ),
    ]
