# Generated by Django 3.2.19 on 2023-05-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='priority_color',
            field=models.IntegerField(blank=True),
        ),
    ]
