# Generated by Django 3.2.19 on 2023-05-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='priority_color',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
