# Generated by Django 3.2.19 on 2023-06-26 17:11

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='file',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='uploads/'),
        ),
    ]
