# Generated by Django 3.2.19 on 2023-06-27 13:01

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_card_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='members',
        ),
        migrations.AlterField(
            model_name='card',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='uploads/'),
        ),
    ]
